# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' cumWeightedSum
#'
#' This function computes the cumulative weighted sum over K nearest neighbors
#'
#' @param Index The matrix of indices
#' @param y A vector of the non-bootstrapped outcomes
#' @param multiplicity A vector of the multiplicity for each nearest neighbors observation
#' @param data Vector of the bootstrapped indices
#' @param K A integer for K
#' @param self_as_NN A boolean where to consider a point itself as its own nearest neighbor
#' @return A list of the weighted sum and number of NN
#' @export
#' @keywords internal
cumWeightedSum <- function(Index, y, multiplicity, data, K, self_as_NN = FALSE) {
    .Call(`_causalKNN_cumWeightedSum`, Index, y, multiplicity, data, K, self_as_NN)
}

#' cumWeightedSumStep
#'
#' This function computes the cumulative weighted sum over K nearest neighbors for a sequence of K values
#'
#' @param Index The matrix of nearest neighbor indices
#' @param y A vector of the non-bootstrapped outcomes
#' @param multiplicity A vector of the multiplicity for each nearest neighbors observation
#' @param data Vector of the bootstrapped indices
#' @param N_steps A integer for the number of steps of K_step to take
#' @param K_step A integer for the value of steps of K and the initial K value
#' @return A list of the weighted sum and number of NN
#' @export
#' @keywords internal
cumWeightedSumStep <- function(Index, y, multiplicity, data, N_steps, K_step) {
    .Call(`_causalKNN_cumWeightedSumStep`, Index, y, multiplicity, data, N_steps, K_step)
}

#' INV_EXC
#'
#' Computes the inverse or the Moore-Penrose pseudo-inverse when \code{supplied} is true. If
#' \code{supplied} is false, then it computes the covariance matrix and then it's inverse.
#'
#' @param cov_data A matrix of the data or the covariance matrix
#' @param supplied A boolean of whether the covariance matrix is supplied.
#' @return The inverse covariance matrix
#' @noRd
INV_EXC <- function(cov_data, supplied = FALSE) {
    .Call(`_causalKNN_INV_EXC`, cov_data, supplied)
}

#' inner_loop
#'
#' Computes the inner loop for the Nearest Neighbor computations
#'
#' @param matrix_1 A matrix of data
#' @param matrix_2 A matrix of data
#' @param i A integer denoting the row index
#' @param row_num A integer denoting the number of rows of matrix_2
#' @param threads A integer for the number of threads to use
#' @param cov_mat A supplied covariance matrix
#' @return A row vector of the computed differences with the Mahalanobis distance metric
#' @noRd
inner_loop <- function(matrix_1, matrix_2, i, row_num, threads, cov_mat) {
    .Call(`_causalKNN_inner_loop`, matrix_1, matrix_2, i, row_num, threads, cov_mat)
}

#' train_mat
#'
#' Finds the k Nearest Neighbors for the matrix
#'
#' @param MATRIX A matrix of the data
#' @param k An integer of the nearest neighbors to find
#' @param threads An integer of threads to use for Open MP
#' @param COV_MAT The supplied covariance matrix
#' @return A list of the k nearest neighbor indices and distances
#' @noRd
train_mat <- function(MATRIX, k, threads, COV_MAT) {
    .Call(`_causalKNN_train_mat`, MATRIX, k, threads, COV_MAT)
}

#' test_mat
#'
#' Finds k Nearest Neighbors of the Test Data in the Training Data
#'
#' @param MATRIX A matrix of the training data
#' @param TEST_DATA A matrix of the test data
#' @param k An integer of the nearest neighbors to find
#' @param threads An integer of threads to use for Open MP
#' @param COV_MAT The supplied covariance matrix
#' @return A list of the k nearest neighbor indices and distances
#' @noRd
test_mat <- function(MATRIX, TEST_DATA, k, threads, COV_MAT) {
    .Call(`_causalKNN_test_mat`, MATRIX, TEST_DATA, k, threads, COV_MAT)
}

#' knn_index_dist_rcpp
#'
#' Compute NN for Mahalanobis Distance Matricies and wraps the Rcpp helper functions
#'
#' @param MATRIX A matrix of training data
#' @param TEST_DATA A matrix of test data
#' @param k A integer of the Nearest Neighbors to find
#' @param threads A integer of the number of threads to use with Open MP
#' @param COV_MAT User supplied covariance matrix
#' @return A list of the computed nearest neighbor index matrix and distance matrix
#' @export
#' @keywords internal
knn_index_dist_rcpp <- function(MATRIX, TEST_DATA, k, threads, COV_MAT) {
    .Call(`_causalKNN_knn_index_dist_rcpp`, MATRIX, TEST_DATA, k, threads, COV_MAT)
}

